### ISSUE TITLE
Research Dialogue Popup

### ISSUE THREAD

**Issue by jwalshzalando** [zalando-incubator/solution-center-header#108]
Research/Breakdown new brand selection popup

**Comment by cjhowald** [comment]
Research findings:

### Dialog solution
- The [ng2 dialog](https://github.bus.zalan.do/norris/insights-frontend/tree/master/src/app/shared/dialog) developed in Insights Manager FE is not viable for this solution
  - An ng1 component (i.e. the header) cannot directly include an ng2 component
  - To use ng1 and ng2 components together, the main application must bootstrap both frameworks and upgrade/downgrade components as necessary using the upgrade utility. I tried this out and it is a significant effort to get it working.
  - This means consumers of the header would have to do this significant manual effort to use a new version of the header including the ng2 dialog component.
  - The dialog component is just a component and has no service wrapper opening and closing, so this would need to be developed.
  - The dialog component is still part of the insights frontend. If we wanted to release it as a part of the header, we would want to create a new dress-code-ng2-components OS repo and move it into there. Not a significant effort, but some additional overhead to get this feature off the ground.
- We can use [ngDialog](https://github.com/likeastore/ngDialog), our current ng1 dialog solution for the solution center, to produce a popup from the header.
  - We will need to create a template and borrow some styles from solution-center
  - This requires significantly less setup, and should allow header consumers to simply upgrade their header and it will "just work".
  - The header will have a new dependency on ngDialog, so clients might need to update their dependencies (although npm + a bundler like webpack will solve this automatically).
  - If we upgrade the header to ng2 or some other technology, this solution will need to be ported as well.

Based on the above, my recommendation is that we use ngDialog to implement the dialog. It is a quick win for us and should require minimal or no effort from the header consumers.

### Header API
- To display the popup, the header will need access to all available brands for the user and recent brands. (Note: this will change from brands to business parters with the impending solution center business parter concept redesign.)
- Since the header does not load any data, but rather accepts it as input, the user's current and recent brands will need to be loaded from our APIs (note: the recent brands API is still in design) and passed in to the header. This will require some extra work from all header consumers.

**Comment by cjhowald** [comment]
Closing as the research is complete, and starting the design.
